# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\a5192\OneDrive\Project\jialing\ExcelCompare\Code\QT\test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 689)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_newBeginRowId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_newBeginRowId.setGeometry(QtCore.QRect(40, 170, 51, 21))
        self.lineEdit_newBeginRowId.setObjectName("lineEdit_newBeginRowId")
        self.button_BeginProcess = QtWidgets.QPushButton(self.centralwidget)
        self.button_BeginProcess.setGeometry(QtCore.QRect(490, 460, 101, 23))
        self.button_BeginProcess.setStyleSheet("")
        self.button_BeginProcess.setObjectName("button_BeginProcess")
        self.lineEdit_newSheetNames = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_newSheetNames.setGeometry(QtCore.QRect(40, 120, 451, 31))
        self.lineEdit_newSheetNames.setObjectName("lineEdit_newSheetNames")
        self.lineEdit_newKeyColId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_newKeyColId.setGeometry(QtCore.QRect(40, 210, 51, 21))
        self.lineEdit_newKeyColId.setObjectName("lineEdit_newKeyColId")
        self.lineEdit_newValueColId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_newValueColId.setGeometry(QtCore.QRect(40, 250, 51, 20))
        self.lineEdit_newValueColId.setObjectName("lineEdit_newValueColId")
        self.checkBox_newIfJudgeSpecified = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_newIfJudgeSpecified.setGeometry(QtCore.QRect(40, 290, 431, 16))
        self.checkBox_newIfJudgeSpecified.setObjectName("checkBox_newIfJudgeSpecified")
        self.lineEdit_newJudgeOptions = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_newJudgeOptions.setGeometry(QtCore.QRect(40, 410, 451, 31))
        self.lineEdit_newJudgeOptions.setObjectName("lineEdit_newJudgeOptions")
        self.lineEdit_newJudgeColId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_newJudgeColId.setGeometry(QtCore.QRect(40, 320, 51, 20))
        self.lineEdit_newJudgeColId.setObjectName("lineEdit_newJudgeColId")
        self.lineEdit_baseSheetNames = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_baseSheetNames.setGeometry(QtCore.QRect(600, 120, 451, 31))
        self.lineEdit_baseSheetNames.setObjectName("lineEdit_baseSheetNames")
        self.lineEdit_baseKeyColId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_baseKeyColId.setGeometry(QtCore.QRect(600, 210, 51, 20))
        self.lineEdit_baseKeyColId.setObjectName("lineEdit_baseKeyColId")
        self.lineEdit_baseValueColId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_baseValueColId.setGeometry(QtCore.QRect(600, 250, 51, 20))
        self.lineEdit_baseValueColId.setObjectName("lineEdit_baseValueColId")
        self.checkBox_baseIfJudgeSpecified = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_baseIfJudgeSpecified.setGeometry(QtCore.QRect(600, 290, 431, 16))
        self.checkBox_baseIfJudgeSpecified.setObjectName("checkBox_baseIfJudgeSpecified")
        self.lineEdit_baseJudgeOptions = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_baseJudgeOptions.setGeometry(QtCore.QRect(600, 410, 451, 31))
        self.lineEdit_baseJudgeOptions.setObjectName("lineEdit_baseJudgeOptions")
        self.lineEdit_baseBeginRowId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_baseBeginRowId.setGeometry(QtCore.QRect(600, 170, 51, 21))
        self.lineEdit_baseBeginRowId.setObjectName("lineEdit_baseBeginRowId")
        self.lineEdit_baseJudgeColId = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_baseJudgeColId.setGeometry(QtCore.QRect(600, 320, 51, 20))
        self.lineEdit_baseJudgeColId.setObjectName("lineEdit_baseJudgeColId")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 301, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 170, 161, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 210, 381, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 250, 381, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 320, 411, 20))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 390, 441, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(670, 170, 161, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(670, 250, 381, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(670, 210, 381, 20))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(670, 320, 411, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(600, 390, 441, 20))
        self.label_15.setObjectName("label_15")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 100, 301, 20))
        self.label_2.setObjectName("label_2")
        self.textBrowser_showResult = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_showResult.setGeometry(QtCore.QRect(40, 500, 1011, 131))
        self.textBrowser_showResult.setObjectName("textBrowser_showResult")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 1011, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.button_SelectNewFile = QtWidgets.QPushButton(self.layoutWidget)
        self.button_SelectNewFile.setStyleSheet("")
        self.button_SelectNewFile.setObjectName("button_SelectNewFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.button_SelectNewFile)
        self.Label_ShowNewFlie = QtWidgets.QLabel(self.layoutWidget)
        self.Label_ShowNewFlie.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.Label_ShowNewFlie.setWordWrap(True)
        self.Label_ShowNewFlie.setObjectName("Label_ShowNewFlie")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Label_ShowNewFlie)
        self.button_SelectBaseFile = QtWidgets.QPushButton(self.layoutWidget)
        self.button_SelectBaseFile.setObjectName("button_SelectBaseFile")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.button_SelectBaseFile)
        self.Label_ShowBaseFlie = QtWidgets.QLabel(self.layoutWidget)
        self.Label_ShowBaseFlie.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.Label_ShowBaseFlie.setWordWrap(True)
        self.Label_ShowBaseFlie.setObjectName("Label_ShowBaseFlie")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Label_ShowBaseFlie)
        self.checkBox_newjudgeIn = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_newjudgeIn.setGeometry(QtCore.QRect(40, 360, 401, 16))
        self.checkBox_newjudgeIn.setObjectName("checkBox_newjudgeIn")
        self.checkBox_basejudgeIn = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_basejudgeIn.setGeometry(QtCore.QRect(600, 360, 401, 16))
        self.checkBox_basejudgeIn.setObjectName("checkBox_basejudgeIn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_newBeginRowId.setText(_translate("MainWindow", "1"))
        self.button_BeginProcess.setText(_translate("MainWindow", "Begin Compare"))
        self.lineEdit_newSheetNames.setText(_translate("MainWindow", "Sheet1,Sheet2,Sheet3"))
        self.lineEdit_newKeyColId.setText(_translate("MainWindow", "1"))
        self.lineEdit_newValueColId.setText(_translate("MainWindow", "3"))
        self.checkBox_newIfJudgeSpecified.setText(_translate("MainWindow", "是否需要根据表格内容筛选，比如只选择表格中3班的学生。如果需要就打钩"))
        self.lineEdit_newJudgeOptions.setText(_translate("MainWindow", "1班,2班,3班"))
        self.lineEdit_newJudgeColId.setText(_translate("MainWindow", "1"))
        self.lineEdit_baseSheetNames.setText(_translate("MainWindow", "Sheet3,Sheet4,Sheet5"))
        self.lineEdit_baseKeyColId.setText(_translate("MainWindow", "1"))
        self.lineEdit_baseValueColId.setText(_translate("MainWindow", "3"))
        self.checkBox_baseIfJudgeSpecified.setText(_translate("MainWindow", "是否需要根据表格内容筛选，比如只选择表格中3班的学生。如果需要就打钩"))
        self.lineEdit_baseJudgeOptions.setText(_translate("MainWindow", "2班,3班,4班"))
        self.lineEdit_baseBeginRowId.setText(_translate("MainWindow", "1"))
        self.lineEdit_baseJudgeColId.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "new中需要对比的表格，如果是多个表格以英文逗号分隔"))
        self.label_3.setText(_translate("MainWindow", "需要对比的起始行，从1开始"))
        self.label_4.setText(_translate("MainWindow", "需要对比的关键字所在列，比如按照姓名-学号对比，这里填姓名所在列"))
        self.label_5.setText(_translate("MainWindow", "需要对比的内容所在列，比如按照姓名-学号对比，这里填学号所在列"))
        self.label_7.setText(_translate("MainWindow", "筛选内容所在列，比如选择3班的同学，就把“3班”所在列填入"))
        self.label_9.setText(_translate("MainWindow", "筛选内容比如选择3班的同学，就把“3班”填入，如果是多个表格以英文逗号分隔"))
        self.label_10.setText(_translate("MainWindow", "需要对比的起始行，从1开始"))
        self.label_11.setText(_translate("MainWindow", "需要对比的内容所在列，比如按照姓名-学号对比，这里填学号所在列"))
        self.label_12.setText(_translate("MainWindow", "需要对比的关键字所在列，比如按照姓名-学号对比，这里填姓名所在列"))
        self.label_14.setText(_translate("MainWindow", "筛选内容所在列，比如选择3班的同学，就把“3班”所在列填入"))
        self.label_15.setText(_translate("MainWindow", "筛选内容比如选择3班的同学，就把“3班”填入，如果是多个表格以英文逗号分隔"))
        self.label_2.setText(_translate("MainWindow", "base中需要对比的表格，如果是多个表格以英文逗号分隔"))
        self.button_SelectNewFile.setText(_translate("MainWindow", "new"))
        self.Label_ShowNewFlie.setText(_translate("MainWindow", "x"))
        self.button_SelectBaseFile.setText(_translate("MainWindow", "base"))
        self.Label_ShowBaseFlie.setText(_translate("MainWindow", "x"))
        self.checkBox_newjudgeIn.setText(_translate("MainWindow", "打钩表示只保留筛选内容对应的行，不打钩表示排除筛选内容对应的行"))
        self.checkBox_basejudgeIn.setText(_translate("MainWindow", "打钩表示只保留筛选内容对应的行，不打钩表示排除筛选内容对应的行"))
